name: Semantic Release

on:
  workflow_call:
    inputs:
      node-version:
        description: "Node version to run scripts"
        default: "20.x"
        required: false
        type: string
      dry_run:
        default: false
        description: "Generate version output, but DO NOT create a release or tag"
        type: boolean
        required: false
    outputs:
      version:
        description: "The version created by semantic-release"
        value: ${{ jobs.semantic-release.outputs.version }}

defaults:
  run:
    shell: bash

jobs:
  semantic-release:
    name: Semantic Release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      version: ${{ steps.semantic.new_release_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 21.1.1
          extra_plugins: |
            @semantic-release/commit-analyzer@11
            @semantic-release/release-notes-generator@12
            @semantic-release/changelog@6
            @semantic-release/git@10
            conventional-changelog-conventionalcommits@5
            @semantic-release/github@9
          branches: |
            [
              '+([0-9])?(.{+([0-9]),x}).x',
              'main',
              'next',
              'next-major',
              {
                name: 'beta',
                prerelease: true
              },
              {
                name: 'alpha',
                prerelease: true
              }
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          HUSKY: 0

      - name: Version of Job Summary
        env:
          VERSION: ${{ steps.semantic.outputs.new_release_version }}
        run: |
          if [[ -z "${VERSION}" ]]; then
            echo "### NO COMMITS TRIGGER A RELEASE" >> $GITHUB_STEP_SUMMARY
          else
            echo "### New Version > ${VERSION}" >> $GITHUB_STEP_SUMMARY
            if "${{ inputs.dry_run }}"; then
              echo " (not yet created because this was a dry_run)" >> $GITHUB_STEP_SUMMARY
            fi
          fi
